### ISSUE TITLE
有没有试试过更小的参数量或者更大的输入图像大小来提高质量

### ISSUE THREAD

**Issue by doubi-killer** [TMElyralab/MuseTalk#100]

**Comment by czk32611** [comment]
Hello，我们尝试使用过更小的参数量，效果有一定下降。

更大的输入图像需要高清的人脸说话数据集，目前比较稀缺。

**Comment by jkla139** [comment]
> Hello，我们尝试使用过更小的参数量，效果有一定下降。
> 
> 更大的输入图像需要高清的人脸说话数据集，目前比较稀缺。

VFHQ 应该可以，512大小人脸，原视频更大，
不过可惜都是国外的，而且应该也没有美颜脸
