### ISSUE TITLE
运行 realtime_inference 时 ffmpeg 报错，Unrecognized option 'crf'，如图所示

### ISSUE THREAD

**Issue by tackhwa** [TMElyralab/MuseTalk#106]
![image](https://github.com/TMElyralab/MuseTalk/assets/55059307/b80c8600-d30c-44c0-a3d6-2d985c600b46)

**Comment by czk32611** [comment]
请问有按照readme里安装ffmpeg吗？ https://github.com/TMElyralab/MuseTalk?tab=readme-ov-file#download-ffmpeg-static

**Comment by git-quanxin** [comment]
@czk32611 您好大佬，可以详细讲解一下ffmpeg安装步骤和安装版本

**Comment by git-quanxin** [comment]
![image](https://github.com/TMElyralab/MuseTalk/assets/169735487/494f343a-7114-45da-af94-b0e832d4762e)
w
我也是报这个错误

**Comment by aidenyzhang** [comment]
https://johnvansickle.com/ffmpeg/
可以在这里下载与你系统对应的 ffmpeg版本，然后加入路径即可。

**Comment by git-quanxin** [comment]
@aidenyzhang 路径在哪里加呀，我是小白，找了一会没有找到

**Comment by aidenyzhang** [comment]
可以参考这里的教程，linux和window的操作不太一样
http://www.manks.top/ffmpeg-install-static.html

**Comment by git-quanxin** [comment]
@aidenyzhang 
![image](https://github.com/TMElyralab/MuseTalk/assets/169735487/1f76992a-4ea4-4c15-a3a1-c6af68a35f81)
我是在windows系统，我只能下载到4.4.2-2这个版本的，这个安装好，配置好系统环境后，然后再musetalk这套代码里，哪些路径需要修改吗

**Comment by git-quanxin** [comment]
我是windows系统
