### ISSUE TITLE
mp4 is not in the upload folder and cannot be accessed.

### ISSUE THREAD

**Issue by Song367** [TMElyralab/MuseTalk#114]
ValueError: File E:\workplace\MuseTalk\results\input\outputxxx_mmajicmixRealv6Fp16_rmmusev_referencenet_caseclx09jgwh0000vsp05s0xtp8c_w960_h1280_t102_nb1_s9241040_p5ff69_w0.001_ms8.0_s0.8_g3.5_c-iclx09_r-cFalse_w0.5_V2_rclx_ipclx_fno.mp4 is not in the upload folder and cannot be accessed.

但是我的视频文件已经上传，我上传了16s 文件但是只有4s 保存了。这是什么问题

**Comment by czk32611** [comment]
请问用的是哪个文件进行推理呢？
