### ISSUE TITLE
face size problem?

### ISSUE THREAD

**Issue by TigerHH6866** [TMElyralab/MuseTalk#116]
any limitation on face size?
for example in 1080x1920 full body video, face would be smaller than upper body 1080x1920, seems small face size result is worse than normal.   
is that right?

**Comment by czk32611** [comment]
I think they should work similarly. What is the size of the face? The model runs with a face size of 256 x 256

**Comment by TigerHH6866** [comment]
> I think they should work similarly. What is the size of the face? The model runs with a face size of 256 x 256

means face Facial region ratio in the image，if it is smaller than some value will cause bad result?

**Comment by czk32611** [comment]
> > I think they should work similarly. What is the size of the face? The model runs with a face size of 256 x 256
> 
> means face Facial region ratio in the image，if it is smaller than some value will cause bad result?

Facial region ratio should not affact the resulsts. What really matters would be the absolute size of the face. Could you share your results?
