### ISSUE TITLE
你好，视频配音中存在多个人物 是怎么做到不同的人说不同的音频呢？

### ISSUE THREAD

**Issue by wangwenjie1314** [TMElyralab/MuseTalk#129]
如下图Readme.md截图所示：

难道是，对视频不同的人说话时分别截取成A\B\C\D等mp4，然后分别使用MuseTalk 改口型，这样也太麻烦了啊。

![image](https://github.com/TMElyralab/MuseTalk/assets/4018406/225887e3-825a-4469-bc8f-0c3414d81e08)

![image](https://github.com/TMElyralab/MuseTalk/assets/4018406/1e374dd7-cfd9-44f6-b874-91024f9e2718)

**Comment by aidenyzhang** [comment]
这个应该属于另一个研究领域了。
可以考虑从音频识别的角度把视频分段。
但是影视剧场景中，经常会出现A说话但是画面中的人确是B，这种场景似乎很难自动识别。
