### ISSUE TITLE
使用视频作为输入，推理后期中画面画质损失。如何解决

### ISSUE THREAD

**Issue by danyow-cheung** [TMElyralab/MuseTalk#13]
很好的工作内容，对于图片作为输入的话。画质肉眼较好。但当视频作为输入的时候，画质会损失的比较严重。该如何解决。
![image](https://github.com/TMElyralab/MuseTalk/assets/76671016/7d105d38-4e36-4ce2-aa32-cce799e62759)

**Comment by itechmusic** [comment]
hello，这种情况不应该。请问方便share你的视频和音频吗？

**Comment by danyow-cheung** [comment]
感谢回复，下面是我的输入视频，此外针对于输入视频我并没有经过musev处理，不知道是否会有影响

https://github.com/TMElyralab/MuseTalk/assets/76671016/1ba83f2d-8a2b-49d9-b958-9189a0e5ca68

**Comment by itechmusic** [comment]
> 感谢回复，下面是我的输入视频，此外针对于输入视频我并没有经过musev处理，不知道是否会有影响
> 
>  github_issues.mp4

没有经过musev处理是不会有影响的。请问具体是指视频第几秒？

**Comment by danyow-cheung** [comment]
> > 感谢回复，下面是我的输入视频，此外针对于输入视频我并没有经过musev处理，不知道是否会有影响
> > github_issues.mp4
> 
> 没有经过musev处理是不会有影响的。请问具体是指视频第几秒？

具体在视频的14s到最后，重述问题是出来的图片会有一些方形格，掉帧的情况出现，具体的图片已贴出。感谢解答！

**Comment by danyow-cheung** [comment]
出现原因是因为ffmpeg的命令我有进行变动所以输出的视频画面是有部分模糊的。很好的项目。多谢
