### ISSUE TITLE
Loading pre-trained weights

### ISSUE THREAD

**Issue by hyqlat** [TMElyralab/MuseTalk#133]
Hi, great work! I have a question regarding the loading of the pre-trained weight from "./models/dwpose/dw-ll_ucoco_384.pth". However, I encountered an error:
```
magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```

**Comment by hyqlat** [comment]
具体是在加载dw-ll_ucoco_384.pth时候的报错：
<img width="1043" alt="image" src="https://github.com/TMElyralab/MuseTalk/assets/48561202/7f583f95-0aba-405f-80b1-de11edb8dc82">
是模型更新的问题吗？期待您的回复，谢谢！

**Comment by hyqlat** [comment]
具体是在加载模型时候的报错：
<img width="790" alt="image" src="https://github.com/TMElyralab/MuseTalk/assets/48561202/fa498d2c-80db-46c3-bd38-31868ea07bac">

<img width="1042" alt="image" src="https://github.com/TMElyralab/MuseTalk/assets/48561202/5835fc8b-a771-4e0d-bf8c-3acebe6063cb">

**Comment by czk32611** [comment]
Did you try re-downloading dwpose model？

**Comment by hyqlat** [comment]
> Did you try re-downloading dwpose model？

Thank you! It seems that the network is causing the issue.
