### ISSUE TITLE
这个项目是用CPU在跑吗？GPU没怎么用上。

### ISSUE THREAD

**Issue by LeoLee5008** [TMElyralab/MuseTalk#134]
CPU:13900k，几乎满载在运行，但CPU4090似乎没怎么用，这是什么问题？
![图片1](https://github.com/TMElyralab/MuseTalk/assets/168154957/fedf3ef6-898c-4c8a-84f6-191dc74c9a2f)

**Comment by yaleimeng** [comment]
有些步骤是在CPU上工作（占用率很低），有些步骤是在GPU上工作（占用率逼近满载）。你可以看占用率变化和显存占用情况。
另外源码存在优化的空间，可以自由发挥。

**Comment by aidenyzhang** [comment]
预处理阶段，如视频拆帧，确实是CPU处理的任务。
生成的部分还是需要用到GPU的，主要在U-Net和VAE。
