### ISSUE TITLE
Encountered GPU OOM when trainning.

### ISSUE THREAD

**Issue by pigmeetsomebody** [TMElyralab/MuseTalk#141]
Is training this mode consuming large memory? 
When I finally run the train code, it is stopped due to GPU OOM.
![image](https://github.com/TMElyralab/MuseTalk/assets/60172449/3a591e19-a835-4788-9bdf-f671003bc9ed)
The console output says this process has 23.38 GiB memory in use. Of the allocated memory 21.43 GiB is allocated by PyTorch, and 1.50 GiB is reserved by PyTorch but unallocated. 
How to reduce the memory occupation when running the train code?

**Comment by alexLIUMinhao** [comment]
Was the batch size large during your training?  This would likely consume a significant amount of GPU memory.
