### ISSUE TITLE
How many minutes of Chinese data were used when training the model?

### ISSUE THREAD

**Issue by XH-B** [TMElyralab/MuseTalk#146]
The model you trained works very well, but we use our data （about 2000 minutes) to train our model，the lip is bad and image is blur. Do you have any suggestions? Thanks

**Comment by huyduong7101** [comment]
Hi @XH-B , may I see your loss visualization on tensorboard? I trained MuseTalk with other language, but loss did not decrease much and the outputs are out-of-sync

**Comment by XH-B** [comment]
the result is not saved, but i can tell you the changing of it, from 0.70
to 0.22

huyduong7101 ***@***.***> 于2024年7月31日周三 16:26写道：
