### ISSUE TITLE
最新更新的代码运行 py app.py出现下面的问题 

### ISSUE THREAD

**Issue by anstonjie** [TMElyralab/MuseTalk#15]
ImportError: cannot import name 'ForkProcess' from 'multiprocessing.context'

**Comment by zhangjinyan888** [comment]
就不是在win系统上使用的

**Comment by anstonjie** [comment]
我在pycharm 上搭建的虚拟环境，运行命令没有问题，但是运行 py app.py出现那个问题

**Comment by yhqqxq** [comment]
改成SpawnProcess就可以运行了

**Comment by slayerfrank** [comment]
windows 下 改这里  
![2024-04-23_21-01-57](https://github.com/TMElyralab/MuseTalk/assets/36400196/0a16ccf7-07ac-4d41-8556-48c2af6df826)
