### ISSUE TITLE
Using Whisper instead of Wav2Vec2

### ISSUE THREAD

**Issue by huyduong7101** [TMElyralab/MuseTalk#151]
Hi all, among studies about Talking Face Generation, it is noticed that Wav2Vec2, HuBERT and Melspectrogram are used to extract audio semantic information. I wonder why the authors of MuseTalk adopt Whisper?
In addition, Wav2Vec2 and HuBERT were proposed to speech representation, while Whisper is used for audio speech recognition. Hence, I think Wav2Vec2 and HuBERT seem to be better than Whisper in the manner of Talking Face Generation.

**Comment by xiankgx** [comment]
This works uses the output activations from 5 layers in whisper. The first layer is very close to the input Melspectogram.

**Comment by czk32611** [comment]
> Hi all, among studies about Talking Face Generation, it is noticed that Wav2Vec2, HuBERT and Melspectrogram are used to extract audio semantic information. I wonder why the authors of MuseTalk adopt Whisper? In addition, Wav2Vec2 and HuBERT were proposed to speech representation, while Whisper is used for audio speech recognition. Hence, I think Wav2Vec2 and HuBERT seem to be better than Whisper in the manner of Talking Face Generation.

Actually We did not perform alation study on the audio feature. We used Whisper primarily because it was newer than others.
