### ISSUE TITLE
开源讨论社区

### ISSUE THREAD

**Issue by liuzysy** [TMElyralab/MuseTalk#152]
建了一个开源讨论的社区群，如果有愿意一起分享经验交流的小伙伴可以加入，谢谢
![a1b8fb269e4d549d1529eb3b6cdba21](https://github.com/user-attachments/assets/5717f7b6-d29f-4349-a5af-f4b0166b1a89)

**Comment by Embracex1998** [comment]
zgod0425拉我

**Comment by miumiuc** [comment]
能更新一下二维码吗

**Comment by ZhouYaoxue** [comment]
兄弟可以拉我一下吗~
