### ISSUE TITLE
input video length and input audio length should be the same?

### ISSUE THREAD

**Issue by XingWang1234** [TMElyralab/MuseTalk#153]
I want to ask do we need to keep input video length and input audio length the same?
what about if audio is longer than video?

**Comment by yaleimeng** [comment]
if audio is longer than video ，it will repeat the driven video frames from the beginning.

**Comment by XingWang1234** [comment]
@yaleimeng Thank you so much.

**Comment by czk32611** [comment]
> if audio is longer than video ，it will repeat the driven video frames from the beginning.

Actually it repeats the driven video from the end to the beginning, so that the results remain time-consistent.
