### ISSUE TITLE
预处理阶段视频拆帧

### ISSUE THREAD

**Issue by miumiuc** [TMElyralab/MuseTalk#155]
请问保存在results里面的帧，训练时还会用到嘛，我用多个视频进行训练的话，预处理阶段会保存所有视频的帧，占用大量磁盘空间，如果待提取人脸结束，我在哪里删除帧呢，非常感谢您的回答！

**Comment by zhangziliang04** [comment]
有一个参数是是否复用，预处理的数据，你具体检查一下，默认值设置为True、可以起到加速的作用。--use_saved_coord

**Comment by miumiuc** [comment]
> 有一个参数是是否复用，预处理的数据，你具体检查一下，默认值设置为True、可以起到加速的作用。--use_saved_coord

感谢感谢，但是这个参数是使用提取的人脸图像吧，我想删的是原始帧，已经解决啦～感谢您～
