### ISSUE TITLE
动物的口型驱动

### ISSUE THREAD

**Issue by mmlingyu** [TMElyralab/MuseTalk#157]
动物的口型识别这块有问题 有计划支持么，或者有建议的方法么

**Comment by yaleimeng** [comment]
个人浅见，动物的口型大部分音节都只用关心嘴巴的开、合程度，比人的口型简单很多。
结合你是真实动物还是卡通动物，应该有一些特定的方案。需要一些材料和方案设计，专门训练模型（不同动物估计还不能通用）。

**Comment by zhangziliang04** [comment]
动物口型目前已知的，好像只有facebook发过一个，具体名字忘记了。你搜一下。

**Comment by aidenyzhang** [comment]
MuseTalk是一种inpating生成嘴型的方案，这一类方案生成的嘴型与数据强相关。
我们的训练数据只有真人，所以无法动物的口型生成。即使用在动物身上，大概率会给动物生成一个像人的嘴型。
可以考虑试SadTalker/ LivePortrait这一类基于warping的方案。
