### ISSUE TITLE
unet输入输出尺寸的问题

### ISSUE THREAD

**Issue by ljiqy** [TMElyralab/MuseTalk#161]
您好，musetalk.json里"sample_size": 64,这个参数应该是描述unet输入输出大小的，但是inference时输入unet的latent_batch的维度是[batch_size, 8, 32, 32]，unet输出的维度也是[batch_size, 4, 32, 32]，输入输出都是不是64，请问这是什么原因？

**Comment by czk32611** [comment]
hello, musetalk.json忘记改了。实际输入是[batch_size, 8, 32, 32]

**Comment by Echo-jyt** [comment]
> hello, musetalk.json忘记改了。实际输入是[batch_size, 8, 32, 32]

您好，musetalk.json里面的"sample_size"不修改会对训练结果有影响吗？
