### ISSUE TITLE
应该如何提速，我在A100上生成40s的视频需要5、6分钟，有点慢，大佬们，有解决方案吗？

### ISSUE THREAD

**Issue by hjj-lmx** [TMElyralab/MuseTalk#167]

**Comment by czk32611** [comment]
第一次生成时，由于要提取素材的embedding等数据，所以耗时比较久。如果是同一个素材生成多段语音，可以使用[Real-time inference](![image](https://github.com/user-attachments/assets/4cb460f0-ea58-4840-bf96-be241131c071))流程大大缩短时间。

**Comment by hjj-lmx** [comment]
> 第一次生成时，由于要提取素材的embedding等数据，所以耗时比较久。如果是同一个素材生成多段语音，可以使用Real-time inference流程大大缩短时间。
Real-time inference这个具体怎么使用，我需要封装成api形式

**Comment by zhangziliang04** [comment]
提供一个推理用的视频信息，包括：分辨率，帧率和码率。我帮你看一下。最好附带上视频文件。
