### ISSUE TITLE
嘴巴和胡子对于口型识别的影响

### ISSUE THREAD

**Issue by mmlingyu** [TMElyralab/MuseTalk#169]
目前有的形象有胡子 ，但是都有基本的嘴部特征，最后输出的效果 有的嘴部就糊了. 请问有什么办法可以针对性的调优,或者训练 以应对可能的情况

**Comment by zhangziliang04** [comment]
这个属于面部细节的损失，参考之前的作者回复。暂时灭有解决方案。
