### ISSUE TITLE
When I putted a image in the video_path, it said "ZeroDivisionError: division by zero"

### ISSUE THREAD

**Issue by kieojk** [TMElyralab/MuseTalk#17]
When I setted test.yaml to "data/video/source.jpg", and putted a image in the video_path.
Running the code, it said "ZeroDivisionError: division by zero"

![360截图20240412034446904](https://github.com/TMElyralab/MuseTalk/assets/41268759/b41e7aae-8f43-4e2c-abb1-782768b3c6cf)

![360截图20240412033855800](https://github.com/TMElyralab/MuseTalk/assets/41268759/bbc72b8f-2302-4be4-8cfb-5c8b875403af)

**Comment by itechmusic** [comment]
Hi there, currently the inference code only support video or a folder containing images as video_path. Maybe you could try putting the jpg in a folder and input the path of folder as video_path. Plz let us know if it work or not.

**Comment by itechmusic** [comment]
Ths problem should be solved now.

**Comment by Hemilibeatriz** [comment]
> Olá, atualmente o código de inferência suporta apenas vídeos ou pastas contendo imagens como video_path. Talvez você possa tentar colocar o jpg em uma pasta e inserir o caminho da pasta como video_path. Por favor, nos avise se funciona ou não.

This works
