### ISSUE TITLE
Support for other whisper models specifically Whisper-medium

### ISSUE THREAD

**Issue by devs-hooked** [TMElyralab/MuseTalk#170]
The problem with using whisper models other than tiny is that the pre-trained models/weights do not work properly with other versions. The encoder and checkpoint functions cause problems due to mismatch in parameter sizes. Are there any different pre-trained weights/models that can work with other whisper models? I've tried searching for another version of dwpose , etc models but no result.

![image](https://github.com/user-attachments/assets/efe6c245-7f74-4f9b-ac68-7509ec8dca97)

**Comment by czk32611** [comment]
Could I ask why would you want to use other whisper models?
