### ISSUE TITLE
How can I improve lip resolution?

### ISSUE THREAD

**Issue by gokula-krishna-dev** [TMElyralab/MuseTalk#172]
I generated this video where the Lip sync is good but low in resolution. Adjusting the bbox parameter doesn't help. Can someone please help resolve this?

https://github.com/user-attachments/assets/8b001342-f693-4a30-bef3-0c7d77f1752e

**Comment by zhangziliang04** [comment]
做一下后置高分就行。

**Comment by dubeno** [comment]
> 做一下后置高分就行。

用什么做？

**Comment by phantomwork** [comment]
What about using GFP-gan after the generation of the video?
