### ISSUE TITLE
修改RESIZED_IMG能否支持高清数据集

### ISSUE THREAD

**Issue by qiuzi** [TMElyralab/MuseTalk#176]
原256分辨率对高清视频效果有限，网络结构是否支持高分辨率？

**Comment by miumiuc** [comment]
改成512能跑

**Comment by qiuzi** [comment]
> 改成512能跑

更高的呢？ 1K以上

**Comment by miumiuc** [comment]
更高的就没有试过了，但理论上应该是可行的

**Comment by hnsywangxin** [comment]
> 改成512能跑

改成512后效果有提升吗

**Comment by qiuzi** [comment]
> > 改成512能跑
> 
> 改成512后效果有提升吗

没有提升

**Comment by hnsywangxin** [comment]
> > > 改成512能跑
> > 
> > 
> > 改成512后效果有提升吗
> 
> 没有提升

好的，谢谢
