### ISSUE TITLE
训练9.4W步纹理效果还能改进吗？

### ISSUE THREAD

**Issue by qiuzi** [TMElyralab/MuseTalk#184]
使用单卡4090，train_batch_size=1 ，数据集超分到1024分辨率进行少量数据测试，RESIZED_IMG = 512

![image](https://github.com/user-attachments/assets/50e14eb6-34d3-4cba-9b57-eca742862738)

唇部与面部纹理一直模糊状态
![val_epoch_94000_0_image](https://github.com/user-attachments/assets/0b507383-d86f-47b6-adc6-255225f4d012)

后续训练还有改进意义吗？

**Comment by qiuzi** [comment]
> train_batch_size=1, gradient accumulate多少呢？

默认的 16

**Comment by liuzysy** [comment]
您是直接使用的开源train_code分支进行的训练嘛？还是自己根据开源代码进行修改后训练的？

**Comment by qiuzi** [comment]
> 您是直接使用的开源train_code分支进行的训练嘛？还是自己根据开源代码进行修改后训练的？

修改了分辨率训练的，原本256采样我换成512

**Comment by miumiuc** [comment]
你是就在这一个人的数据上微调吗，还是很多不同人的数据上

**Comment by qiuzi** [comment]
> 你是就在这一个人的数据上微调吗，还是很多不同人的数据上，看这个牙齿也挺清楚的，没有出现粘连的情况
个人数据而已 没做范

**Comment by thbupt** [comment]
单人微调的口型效果咋样

**Comment by qiuzi** [comment]
> 单人微调的口型效果咋样

没啥优化，和原模型一样

**Comment by langzizhixin** [comment]
数据集进行超分肯定达不到好的训练效果啊，需要自己购买，或者拍摄商用高清数据集。

**Comment by qiuzi** [comment]
> 数据集进行超分肯定达不到好的训练效果啊，需要自己购买，或者拍摄商用高清数据集。

权重没有开放训练，换数据集也没用

**Comment by miumiuc** [comment]
> > 数据集进行超分肯定达不到好的训练效果啊，需要自己购买，或者拍摄商用高清数据集。
> 
> 权重没有开放训练，换数据集也没用
权重没有开放训练，是什么意思？

**Comment by qiuzi** [comment]
> > > 数据集进行超分肯定达不到好的训练效果啊，需要自己购买，或者拍摄商用高清数据集。
> > 
> > 
> > 权重没有开放训练，换数据集也没用
> > 权重没有开放训练，是什么意思？
是我理解错了 不好意思

**Comment by qiuzi** [comment]
大概是vae的缘故，没法像gan那么细节清晰，训练集与算力要求太高，训练难度确实大

> > > 数据集进行超分肯定达不到好的训练效果啊，需要自己购买，或者拍摄商用高清数据集。
> > 
> > 
> > 权重没有开放训练，换数据集也没用
> > 权重没有开放训练，是什么意思？

**Comment by miumiuc** [comment]
> 大概是vae的缘故，没法像gan那么细节清晰，训练集与算力要求太高，训练难度确实大
> 
> > > > 数据集进行超分肯定达不到好的训练效果啊，需要自己购买，或者拍摄商用高清数据集。
> > > 
> > > 
> > > 权重没有开放训练，换数据集也没用
> > > 权重没有开放训练，是什么意思？

模型训练的是unet，训练unet也没用吗

**Comment by qiuzi** [comment]
> > 大概是vae的缘故，没法像gan那么细节清晰，训练集与算力要求太高，训练难度确实大
> > 
> > > > > 数据集进行超分肯定达不到好的训练效果啊，需要自己购买，或者拍摄商用高清数据集。
> > > > 
> > > > 
> > > > 权重没有开放训练，换数据集也没用
> > > > 权重没有开放训练，是什么意思？
> 
> 模型训练的是unet，训练unet也没用吗

有用，但效果跟预期不理想，30W步还是看不到牙齿纹理，dhlive 训练用gan 效果更好些

**Comment by langzizhixin** [comment]
啥也不说了，直接上图。
![95faab6d7e5571ae651d342336089af](https://github.com/user-attachments/assets/3877d245-1d42-4487-a353-6dccbe1d040b)

**Comment by qiuzi** [comment]
> 啥也不说了，直接上图。 ![95faab6d7e5571ae651d342336089af](https://private-user-images.githubusercontent.com/74521932/368392132-3877d245-1d42-4487-a353-6dccbe1d040b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MjgwOTgsIm5iZiI6MTcyNjYyNzc5OCwicGF0aCI6Ii83NDUyMTkzMi8zNjgzOTIxMzItMzg3N2QyNDUtMWQ0Mi00NDg3LWEzNTMtNmRjY2JlMWQwNDBiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDAyNDk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMTBkYzQ4MmMyNzk5YWJjODc4ZTliZDFkY2JkZDlmYzdmOWZjYWI2Y2IzOTc1MjljY2MyZDVlNmY1N2EyZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OwUyejjZtp4idcv15tbz56GW9b4tj8m74Oc1c-VDCWw)

多少步？ 嘴唇纹理不够还原
