### ISSUE TITLE
训练与推理对音频的预处理不一样是什么原因？这个会对模型推理的效果有影响吗

### ISSUE THREAD

**Issue by zhangyuzyy** [TMElyralab/MuseTalk#185]
请问一下，训练与推理对音频的预处理不一样是为什么？
训练：
    使用/scripts/data.py中的代码
    whisper_feature = audio_processor.audio2feat(audio_path)
    将whisper_feature 保存成了npy，然后使用DataLoader
   
 
推理时使用的scripts/finetuned_inference.py中的代码
    whisper_feature = audio_processor.audio2feat(audio_path)
    whisper_chunks = audio_processor.feature2chunks(feature_array=whisper_feature,fps=fps)

为什么在训练的时候，不需要使用 audio_processor.feature2chunks方法呢？

**Comment by czk32611** [comment]
hello，在[https://github.com/TMElyralab/MuseTalk/blob/train_codes/train_codes/DataLoader.py#L195](https://github.com/TMElyralab/MuseTalk/blob/train_codes/train_codes/DataLoader.py#L195)进行feature2chunks了。这样保存的空间会小一些

**Comment by zhangyuzyy** [comment]
感谢，理解了
