### ISSUE TITLE
训练完成的model.safetensors如何导入到推理中？

### ISSUE THREAD

**Issue by qiuzi** [TMElyralab/MuseTalk#187]
使用`python -m scripts.finetuned_inference --inference_config configs/inference/test.yaml --unet_checkpoint ./train_codes/checkpoint-390000/` 发现依旧加载 ./models/musetalk/pytorch_model.bin 没能达到512分辨率训练效果。

checkpoint-390000该如何转换成有效pytorch_model.bin模型？

**Comment by liuzysy** [comment]
大佬解决了嘛，同样有这样的问题

**Comment by liuzysy** [comment]
您的390000训练了多久，我现在训练到5800步就用了24h

**Comment by qiuzi** [comment]
> 您的390000训练了多久，我现在训练到5800步就用了24h

7天

**Comment by liuzysy** [comment]
> > 您的390000训练了多久，我现在训练到5800步就用了24h
> 
> 7天

请问您修改了什么配置导致训练速度增加了，我这个速度想跑这么多步得一个多月，用的A100单卡

**Comment by qiuzi** [comment]
> > > 您的390000训练了多久，我现在训练到5800步就用了24h
> > 
> > 7天
> 
> 请问您修改了什么配置导致训练速度增加了，我这个速度想跑这么多步得一个多月，用的A100单卡

没改啥呀 原模型不支持256以上分辨率的训练，步数再多也没用

**Comment by gg22mm** [comment]
在哪里有训练代码？

**Comment by qiuzi** [comment]
> 在哪里有训练代码？

另一个分支里

**Comment by gg22mm** [comment]
> pytorch_model.bin

看能不能拿训练的/checkpoint-390000下面的所有文件，覆盖到./models/musetalk/ 下面去试试，记录备份~~

**Comment by qiuzi** [comment]
> > pytorch_model.bin
> 
> 看能不能拿训练的/checkpoint-390000下面的所有文件，覆盖到./models/musetalk/ 下面去试试，记录备份~~

直接报错 因为没有权重

**Comment by langzizhixin** [comment]
##  safetensors 2 bin

import torch
from safetensors.torch import load_file

# 需要转换的safetensors文件路径
safetensors_file_path = 'models/musetalk/model.safetensors'

# 加载safetensors文件
pt_state_dict = load_file(safetensors_file_path, device="cpu")

# 保存为bin文件
torch.save(pt_state_dict, 'models/musetalk/pytorch_model.bin')

**Comment by langzizhixin** [comment]
##  将safetensors转换成bin
import torch
from safetensors.torch import load_file
safetensors_file_path = 'models/musetalk/model.safetensors'
pt_state_dict = load_file(safetensors_file_path, device="cpu")
torch.save(pt_state_dict, 'models/musetalk/pytorch_model.bin')

**Comment by qiuzi** [comment]
真的很棒

> ## 将safetensors转换成bin
> import torch from safetensors.torch import load_file safetensors_file_path = 'models/musetalk/model.safetensors' pt_state_dict = load_file(safetensors_file_path, device="cpu") torch.save(pt_state_dict, 'models/musetalk/pytorch_model.bin')

**Comment by foreverhell** [comment]
训练完成之后怎么把权重转成和原来unet一样的bin格式，而不需要用accelerator再导入一次？

**Comment by foreverhell** [comment]
训练完成之后是pt格式，而且有model_states和optim_states，怎么把权重转成和原来unet一样的bin格式，而不需要用accelerator再导入一次？因为不是safetensors格式，所以不能用楼上的方法

**Comment by qiuzi** [comment]
> 训练完成之后是pt格式，而且有model_states和optim_states，怎么把权重转成和原来unet一样的bin格式，而不需要用accelerator再导入一次？因为不是safetensors格式，所以不能用楼上的方法

我已经提取出来了
