### ISSUE TITLE
data processing处理后保存的帧数不同

### ISSUE THREAD

**Issue by liuzysy** [TMElyralab/MuseTalk#188]
使用最新的data_new.sh进行数据预处理以后发现，保存到results种crop后的视频帧数和.npy是相同的，但是保存到/data/images中的png数量要少很多，这是什么技术原因需要这样的操作而不是直接把results中crop后的png直接保存在/data/images里面？求告知谢谢

**Comment by miumiuc** [comment]
我也发现了这个问题，请问你知道原因了吗，data_new.sh还有老版本吗
