### ISSUE TITLE
error while installation

### ISSUE THREAD

**Issue by txqphuong** [TMElyralab/MuseTalk#192]
hi folks, im trying to use this model but i got an error while install requirements.txt:

pip install -r requirements.txt
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
ERROR: Ignored the following yanked versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3
ERROR: Could not find a version that satisfies the requirement torchvision==0.15.2 (from versions: 0.1.6, 0.2.0, 0.17.0, 0.17.0+cu118, 0.17.1, 0.17.1+cu118, 0.17.2, 0.17.2+cu118, 0.18.0, 0.18.0+cu118, 0.18.1, 0.18.1+cu118, 0.19.0, 0.19.0+cu118, 0.19.1, 0.19.1+cu118)
ERROR: No matching distribution found for torchvision==0.15.2

i have install pytorch before:
python -c "import torch; print(torch.__version__)"
>> 2.3.0+cpu

how can i solve this problem, thank you.

**Comment by Hasan0ff** [comment]
install it in a conda virtual environment.
