### ISSUE TITLE
视频与音频组合。为什么视频里是嘴巴部分是黑的？原始图片帧都正常。是哪个参数没打开么？

### ISSUE THREAD

**Issue by apple1li** [TMElyralab/MuseTalk#193]

**Comment by liubai021** [comment]
我也遇到同样的问题，请问你解决了吗

**Comment by apple1li** [comment]
> 我也遇到同样的问题，请问你解决了吗
用4090云算力卡就好了。原电脑不行，不知道哪里问题

**Comment by apple1li** [comment]
> 我也遇到同样的问题，请问你解决了吗

不确定是否完全是算力影响

**Comment by liubai021** [comment]
> > 我也遇到同样的问题，请问你解决了吗
> > 用4090云算力卡就好了。原电脑不行，不知道哪里问题

那可能也是我显卡的问题，我准备换个好点的再试试看

**Comment by liubai021** [comment]
> > 我也遇到同样的问题，请问你解决了吗
> 
> 不确定是否完全是算力影响

我用别的试了没什么问题，大概率就是显存的问题了
