### ISSUE TITLE
拿到的原始视频本身是在不断说话的，如何能生成闭嘴的视频？

### ISSUE THREAD

**Issue by ThornbirdZhang** [TMElyralab/MuseTalk#202]
拿到人物形象视频是不断在说话的，推理时候使用静音音频，输出的图像还是原先张嘴说话的视频。
有没有办法生成人物闭嘴的视频？

**Comment by YZX-codesky** [comment]
有办法解决了吗？

**Comment by ThornbirdZhang** [comment]
https://github.com/lipku/LiveTalking/issues/268  有初步的方法，但是效果不是很理想。
