### ISSUE TITLE
如何设置在原有的pytorch_model.bin基础上进行微调训练？

### ISSUE THREAD

**Issue by hdjlcbz** [TMElyralab/MuseTalk#204]
怎么在原有的模型基础上进行微调训练？

**Comment by foreverhell** [comment]
训练代码这个部分
![image](https://github.com/user-attachments/assets/ee355eb1-68f0-4efc-9d5b-9439f1b404a6)
把权重导入
weights = torch.load(unet_path)
unet.load_state_dict(weights)

**Comment by hnsywangxin** [comment]
> 训练代码这个部分 ![image](https://private-user-images.githubusercontent.com/70958661/377791783-ee355eb1-68f0-4efc-9d5b-9439f1b404a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1ODI5ODQsIm5iZiI6MTcyOTU4MjY4NCwicGF0aCI6Ii83MDk1ODY2MS8zNzc3OTE3ODMtZWUzNTVlYjEtNjhmMC00ZWZjLTlkNWItOTQzOWYxYjQwNGE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDA3MzgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxYmNhYzc4NTg4Yzk3OGM2MjUzZTg3ZDI1NDVhY2YwM2FmYjYzMWYyMzgxZmYxMzQxNjNjZjdkZmRkMTZkMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YneNlawJped3zI-_Ti59uK9V6eh9xqYBclgKVrcKxaE) 把权重导入 weights = torch.load(unet_path) unet.load_state_dict(weights)

按照该代码加载了权重，光unet显存占用都将近30G,然后bs=1都会报OOM(我每个卡40G显存)，请问你也是消耗这么多显存嘛

**Comment by foreverhell** [comment]
> > 训练代码这个部分 ![image](https://private-user-images.githubusercontent.com/70958661/377791783-ee355eb1-68f0-4efc-9d5b-9439f1b404a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1ODI5ODQsIm5iZiI6MTcyOTU4MjY4NCwicGF0aCI6Ii83MDk1ODY2MS8zNzc3OTE3ODMtZWUzNTVlYjEtNjhmMC00ZWZjLTlkNWItOTQzOWYxYjQwNGE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDA3MzgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxYmNhYzc4NTg4Yzk3OGM2MjUzZTg3ZDI1NDVhY2YwM2FmYjYzMWYyMzgxZmYxMzQxNjNjZjdkZmRkMTZkMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YneNlawJped3zI-_Ti59uK9V6eh9xqYBclgKVrcKxaE) 把权重导入 weights = torch.load(unet_path) unet.load_state_dict(weights)
> 
> 按照该代码加载了权重，光unet显存占用都将近30G,然后bs=1都会报OOM(我每个卡40G显存)，请问你也是消耗这么多显存嘛

是，weights可以先放在CPU上，保证unet在GPU就行

**Comment by hdjlcbz** [comment]
> > > 训练代码这个部分 ![image](https://private-user-images.githubusercontent.com/70958661/377791783-ee355eb1-68f0-4efc-9d5b-9439f1b404a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1ODI5ODQsIm5iZiI6MTcyOTU4MjY4NCwicGF0aCI6Ii83MDk1ODY2MS8zNzc3OTE3ODMtZWUzNTVlYjEtNjhmMC00ZWZjLTlkNWItOTQzOWYxYjQwNGE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDA3MzgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxYmNhYzc4NTg4Yzk3OGM2MjUzZTg3ZDI1NDVhY2YwM2FmYjYzMWYyMzgxZmYxMzQxNjNjZjdkZmRkMTZkMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YneNlawJped3zI-_Ti59uK9V6eh9xqYBclgKVrcKxaE) 把权重导入 weights = torch.load(unet_path) unet.load_state_dict(weights)
> > 
> > 
> > 按照该代码加载了权重，光unet显存占用都将近30G,然后bs=1都会报OOM(我每个卡40G显存)，请问你也是消耗这么多显存嘛
> 
> 是，weights可以先放在CPU上，保证unet在GPU就行

那么在这个权重基础上去训练他的那个数据集，效果会更好吗？

**Comment by hnsywangxin** [comment]
> > > 训练代码这个部分 ![image](https://private-user-images.githubusercontent.com/70958661/377791783-ee355eb1-68f0-4efc-9d5b-9439f1b404a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1ODI5ODQsIm5iZiI6MTcyOTU4MjY4NCwicGF0aCI6Ii83MDk1ODY2MS8zNzc3OTE3ODMtZWUzNTVlYjEtNjhmMC00ZWZjLTlkNWItOTQzOWYxYjQwNGE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDA3MzgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxYmNhYzc4NTg4Yzk3OGM2MjUzZTg3ZDI1NDVhY2YwM2FmYjYzMWYyMzgxZmYxMzQxNjNjZjdkZmRkMTZkMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YneNlawJped3zI-_Ti59uK9V6eh9xqYBclgKVrcKxaE) 把权重导入 weights = torch.load(unet_path) unet.load_state_dict(weights)
> > 
> > 
> > 按照该代码加载了权重，光unet显存占用都将近30G,然后bs=1都会报OOM(我每个卡40G显存)，请问你也是消耗这么多显存嘛
> 
> 是，weights可以先放在CPU上，保证unet在GPU就行

已解决，谢谢

**Comment by sswax000643** [comment]
> > > > 训练代码这个部分 ![image](https://private-user-images.githubusercontent.com/70958661/377791783-ee355eb1-68f0-4efc-9d5b-9439f1b404a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1ODI5ODQsIm5iZiI6MTcyOTU4MjY4NCwicGF0aCI6Ii83MDk1ODY2MS8zNzc3OTE3ODMtZWUzNTVlYjEtNjhmMC00ZWZjLTlkNWItOTQzOWYxYjQwNGE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDA3MzgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxYmNhYzc4NTg4Yzk3OGM2MjUzZTg3ZDI1NDVhY2YwM2FmYjYzMWYyMzgxZmYxMzQxNjNjZjdkZmRkMTZkMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YneNlawJped3zI-_Ti59uK9V6eh9xqYBclgKVrcKxaE) 把权重导入 weights = torch.load(unet_path) unet.load_state_dict(weights)
> > > 
> > > 
> > > 按照该代码加载了权重，光unet显存占用都将近30G,然后bs=1都会报OOM(我每个卡40G显存)，请问你也是消耗这么多显存嘛
> > 
> > 
> > 是，weights可以先放在CPU上，保证unet在GPU就行
> 
> 已解决，谢谢


请问是如何解决的呢？可以分享下吗，我现在也是加载权重就爆显存

**Comment by hnsywangxin** [comment]
@sswax000643 问下gpt，或者谷歌查一下，有个关键字参数，这个不难
