### ISSUE TITLE
v100下实时推理30+fps是如何做到的？

### ISSUE THREAD

**Issue by leafopening** [TMElyralab/MuseTalk#205]
我在32G显存的v100下跑实时推理示例：python -m scripts.realtime_inference --inference_config configs/inference/realtime.yaml --batch_size 4

得到的结果是“Total process time of 202 frames including saving images = 25.92679262161255s ”。  

配置文件是这样的：
avator_1:
 preparation: False
 bbox_shift: 5
 video_path: "data/video/yongen.mp4"
 audio_clips:
     audio_0: "data/audio/yongen.wav"
 
请问如何调整？？

**Comment by czk32611** [comment]
https://github.com/TMElyralab/MuseTalk/issues/49#issuecomment-2081429256 这里有我们的测速结果，你可以对比一下
