### ISSUE TITLE
No module named scripts.inference

### ISSUE THREAD

**Issue by ffhelly** [TMElyralab/MuseTalk#210]
python -m scripts.inference --inference_config configs/inference/test.yaml

error  message :  No module named scripts.inference

but ,  i used  pip install scripts ， and  successed this  install.

its same error message。

**Comment by vincentWuK** [comment]
cd scripts and create empty __init__.py

**Comment by vincentWuK** [comment]
or just try to run it by python scripts/inference --inference_config configs/inference/test.yaml

**Comment by ffhelly** [comment]
> or just try to run it by python scripts/inference --inference_config configs/inference/test.yaml

thx,bro.

I tried running the program using this method and eventually found that my MMCV framework doesn't seem to match. My current CUDA version is 12.3, but the MMCV prompt version is 11. Is it necessary to downgrade CUDA?

The detected CUDA version (12.3) mismatches the version that was used to compile
PyTorch (11.7).  Please make sure to use the same CUDA versions.

**Comment by vincentWuK** [comment]
> > or just try to run it by python scripts/inference --inference_config configs/inference/test.yaml
> 
> thx,bro.
> 
> I tried running the program using this method and eventually found that my MMCV framework doesn't seem to match. My current CUDA version is 12.3, but the MMCV prompt version is 11. Is it necessary to downgrade CUDA?
> 
> The detected CUDA version (12.3) mismatches the version that was used to compile PyTorch (11.7). Please make sure to use the same CUDA versions.

you can first try to use conda for managing cuda environment. if not works, try to use devcontainer in vscode.

**Comment by vincentWuK** [comment]
conda create -> conda activate -> python3 -m pip install pytorch and pytorch-cuda, ....

**Comment by ffhelly** [comment]
> conda create -> conda activate -> python3 -m pip install pytorch and pytorch-cuda, ....


Do you mean to create a new conda environment, point to the corresponding pytorch version (11), and then deploy it?
Will the 12.2 version I saw in Nvidia smi conflict with the current new conda version environment? bro
