### ISSUE TITLE
NameError: name 'copy' is not defined

### ISSUE THREAD

**Issue by TigerHH6866** [TMElyralab/MuseTalk#212]
*********************************
  creating avator: 12345
*********************************
preparing data materials ... ...
extracting landmarks...
reading images...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1224/1224 [00:52<00:00, 23.51it/s]
get key_landmark and face bounding boxes with the bbox_shift: 11
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1224/1224 [03:38<00:00,  5.61it/s]
********************************************bbox_shift parameter adjustment**********************************************************
Total frame:「1224」 Manually adjust range : [ -15~15 ] , the current value: 11
*************************************************************************************************************************************
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2448/2448 [06:57<00:00,  5.86it/s]
Inferring using: input/12345-01.wav
start inference
video in 25 FPS, audio idx in 50FPS
processing audio:input/12345-01.wav costs 101.46450996398926ms
732
  1%|▉                                                                                                                                                                | 1/183 [00:02<06:15,  2.06s/it]Exception in thread Thread-2 (process_frames):
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/autodl-tmp/stable-diffusion-webui/miaoshou/MuseTalk/scripts/realtime_inference.py", line 215, in process_frames
    combine_frame = get_image_blending(ori_frame,res_frame,bbox,mask,mask_crop_box)
  File "/root/autodl-tmp/stable-diffusion-webui/miaoshou/MuseTalk/musetalk/utils/blending.py", line 91, in get_image_blending
    face_large = copy.deepcopy(body[y_s:y_e, x_s:x_e])
NameError: name 'copy' is not defined

**Comment by eoffermann** [comment]
Commit f051221f76437c83f7ef61ed7f1a9788396e16c2 broke this.

Temp fix: add
```
import copy
```
to the top of `musetalk/utils/blending.py`

**Comment by eoffermann** [comment]
Created #213 to resolve.

**Comment by TigerHH6866** [comment]
> Created #213 to resolve.

seem by import copy, realtime running still get error
