### ISSUE TITLE
音频Embedding为什么只取一半

### ISSUE THREAD

**Issue by HuangYongHang1** [TMElyralab/MuseTalk#222]
start_idx = int(emb['start'])
            # 获取结束索引
            end_idx = int(emb['end'])
            # end_idx - start_idx 是片段的总时长。
            # 将时长除以 2，得到的是片段的一半长度，用来从特征数组 encoder_embeddings 中提取相应的部分。
            emb_end_idx = int((end_idx - start_idx)/2)
            embed_list.append(encoder_embeddings[:emb_end_idx])
        concatenated_array = np.concatenate(embed_list, axis=0)
        
        
        这个代码我不太懂，来个大佬解释一下，代码在wishper/audio2feature.py的audio2feat函数里

**Comment by miumiuc** [comment]
我也想问

**Comment by aidenyzhang** [comment]
因为whisper模型有一次pooling。
输入30秒到音频，对应的mel是3000个，但是输出成特征就成了1500。
比如有效音频是10秒，则对应的特征要取前500个。
（1000-0）/2 =500

**Comment by HuangYongHang1** [comment]
> 因为whisper模型有一次pooling。 输入30秒到音频，对应的mel是3000个，但是输出成特征就成了1500。 比如有效音频是10秒，则对应的特征要取前500个。 （1000-0）/2 =500

soga，原来如此
