### ISSUE TITLE
想问问各位大佬我跑出来的脸为什么下半张是黑色的mask？T T

### ISSUE THREAD

**Issue by PigPigchick** [TMElyralab/MuseTalk#223]
![00000000](https://github.com/user-attachments/assets/8348436e-bc9b-48a7-95d4-e80f0be32d47)

**Comment by liulhs** [comment]
你用的是Musetalk_Util上给的WorkFlow吧，这说明你的Musetalk Inference的有问题，他没有生成嘴部的结果，然后Mask里就是黑的，我之前也遇到过。当时我的问题是Vae加载的Vae模型不对，你用Musetalk_Util作者提供的Vae试试

**Comment by PigPigchick** [comment]
> 你用的是Musetalk_Util上给的WorkFlow吧，这说明你的Musetalk Inference的有问题，他没有生成嘴部的结果，然后Mask里就是黑的，我之前也遇到过。当时我的问题是Vae加载的Vae模型不对，你用Musetalk_Util作者提供的Vae试试

非常感谢！！！我也解决了，因为在跑的时候有提示An error occurred while trying to fetch ./models/sd-vae-ft-mse/: Error no file named diffusion_pytorch_model.safetensors found in directory ./models/sd-vae-ft-mse/.然后就加入了pytorch_model.safetensors，但是其实用pytorch_model.bin才能正确跑出来，可能.safetensors格式的模型文件读取有点问题
