### ISSUE TITLE
Not completed generation

### ISSUE THREAD

**Issue by skypro1111** [TMElyralab/MuseTalk#228]
What i do wrong if i got results like this?

https://github.com/user-attachments/assets/8c21a290-21b4-4a98-98af-b9b8528948bf

**Comment by eoffermann** [comment]
I've never seen a result like this.

It would be more helpful to have any console output that you received during the run and to know if you've made any changes to the source code, and whether it has ever worked for you or only given you this result.

**Comment by skypro1111** [comment]
> I've never seen a result like this.
> 
> It would be more helpful to have any console output that you received during the run and to know if you've made any changes to the source code, and whether it has ever worked for you or only given you this result.

`
python3 -m scripts.inference --inference_config configs/inference/test.yaml
add ffmpeg to path
2024-11-24 17:06:34.280345: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-11-24 17:06:35.364240: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Loads checkpoint by local backend from path: ./models/dwpose/dw-ll_ucoco_384.pth
cuda start
{'task_0': {'video_path': 'data/video/yongen.mp4', 'audio_path': 'data/audio/yongen.wav'}, 'task_1': {'video_path': 'data/video/sun.mp4', 'audio_path': 'data/audio/sun.wav', 'bbox_shift': -7}}
video in 25.0 FPS, audio idx in 50FPS
extracting landmarks...time consuming
reading images...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 268/268 [00:03<00:00, 75.74it/s]
get key_landmark and face bounding boxes with the default value
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 268/268 [00:30<00:00,  8.83it/s]
********************************************bbox_shift parameter adjustment**********************************************************
Total frame:「268」 Manually adjust range : [ -21~23 ] , the current value: 0
*************************************************************************************************************************************
start inference
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 26/26 [00:10<00:00,  2.38it/s]
pad talking image to original video
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 202/202 [00:20<00:00,  9.71it/s]
ffmpeg -y -v warning -r 25.0 -f image2 -i ./results/yongen_yongen/%08d.png -vcodec libx264 -vf format=rgb24,scale=out_color_matrix=bt709,format=yuv420p -crf 18 temp.mp4
ffmpeg -y -v warning -i data/audio/yongen.wav -i temp.mp4 ./results/yongen_yongen.mp4
Guessed Channel Layout for Input Stream #0.0 : stereo
result is save to ./results/yongen_yongen.mp4
video in 25.0 FPS, audio idx in 50FPS
extracting landmarks...time consuming
reading images...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 550/550 [00:04<00:00, 122.55it/s]
get key_landmark and face bounding boxes with the bbox_shift: -7
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 550/550 [00:38<00:00, 14.35it/s]
********************************************bbox_shift parameter adjustment**********************************************************
Total frame:「550」 Manually adjust range : [ -9~9 ] , the current value: -7
*************************************************************************************************************************************
start inference
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 71/71 [00:21<00:00,  3.25it/s]
pad talking image to original video
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 564/564 [00:40<00:00, 14.06it/s]
ffmpeg -y -v warning -r 25.0 -f image2 -i ./results/sun_sun/%08d.png -vcodec libx264 -vf format=rgb24,scale=out_color_matrix=bt709,format=yuv420p -crf 18 temp.mp4
ffmpeg -y -v warning -i data/audio/sun.wav -i temp.mp4 ./results/sun_sun.mp4
Guessed Channel Layout for Input Stream #0.0 : mono
result is save to ./results/sun_sun.mp4
`

**Comment by skypro1111** [comment]
fixed by installing next dependencies:
` pip install diffusers==0.27.2 huggingface_hub==0.22.0 transformers==4.39.1`
