### ISSUE TITLE
How to ensure continuity between video frames?

### ISSUE THREAD

**Issue by Echo-jyt** [TMElyralab/MuseTalk#238]
```        
 # to smooth the first and the last frame
frame_list_cycle = frame_list + frame_list[::-1]
coord_list_cycle = coord_list + coord_list[::-1]
input_latent_list_cycle = input_latent_list + input_latent_list[::-1]
```

为什么这样做可以让整个视频帧直接连续性更好？

**Comment by aidenyzhang** [comment]
因为视频的第一帧和最后一帧不一样，如果直接用frame_list会有一个很明显的跳变。
这样逆序播放一下，原视频就可以无限循环下去了。
举个例子，假设原视频4秒，100帧，
frame_list就是[1,2,3,....,97,98,99,100]。第1帧和第100帧之间可能有突变。
frame_list_cycle就会是[1,2,3,....,97,98,99,100,100,99,98,.....,3,2,1,1,2,3...........]

**Comment by amyburden** [comment]
> 因为视频的第一帧和最后一帧不一样，如果直接用frame_list会有一个很明显的跳变。 这样逆序播放一下，原视频就可以无限循环下去了。 举个例子，假设原视频4秒，100帧， frame_list就是[1,2,3,....,97,98,99,100]。第1帧和第100帧之间可能有突变。 frame_list_cycle就会是[1,2,3,....,97,98,99,100,100,99,98,.....,3,2,1,1,2,3...........]

但这样场景的其他内容不就是倒放了么
