### ISSUE TITLE
Getting error with cuda 11.8 , pytorch 2.2.1, conda 

### ISSUE THREAD

**Issue by anujsinha72094** [TMElyralab/MuseTalk#24]
ImportError: /home/ubuntu/miniconda3/envs/myenv/lib/python3.10/site-packages/mmcv/_ext.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops10zeros_like4callERKNS_6TensorEN3c108optionalINS5_10ScalarTypeEEENS6_INS5_6LayoutEEENS6_INS5_6DeviceEEENS6_IbEENS6_INS5_12MemoryFormatEEE

**Comment by itechmusic** [comment]
Sorry, we are not very familiar with installing `mmcv` for different versions and platforms. Maybe you could ask [https://github.com/open-mmlab/mmcv](https://github.com/open-mmlab/mmcv)
