### ISSUE TITLE
如何替换vae为自己预训练的vqvae

### ISSUE THREAD

**Issue by Echo-jyt** [TMElyralab/MuseTalk#242]
您好，我自己预训练一个vqvae，如何把代码中的vae替换成我的呢？

**Comment by aidenyzhang** [comment]
可以参考这个函数
https://github.com/TMElyralab/MuseTalk/blob/main/musetalk/models/vae.py#L24

**Comment by Echo-jyt** [comment]
> 可以参考这个函数 https://github.com/TMElyralab/MuseTalk/blob/main/musetalk/models/vae.py#L24

谢谢！已解决！
