### ISSUE TITLE
最后合成的时候太慢了

### ISSUE THREAD

**Issue by angenet** [TMElyralab/MuseTalk#25]
每次进行到pad talking image to original video这个地方的时候，速度非常慢，4090的显卡也只能有10it/s的样子，CPU,GPU和内存的占用都非常小，不知道是不是还有优化的地方

**Comment by itechmusic** [comment]
这里慢的原因是因为在使用`face-parse-bisent`进行人脸分割，以便于将生成的脸贴会到原始的脸上。在实时口型推理场景，人脸分割可以提前进行并存储，我们预计在接下来两周内release用于实时口型推理场景的素材准备代码与实时推理代码。

**Comment by jinqinn** [comment]
厉害

> 这里慢的原因是因为在使用`face-parse-bisent`进行人脸分割，以便于将生成的脸贴会到原始的脸上。在实时口型推理场景，人脸分割可以提前进行并存储，我们预计在接下来两周内release用于实时口型推理场景的素材准备代码与实时推理代码。

**Comment by Xmenlin** [comment]
> 这里慢的原因是因为在使用`face-parse-bisent`进行人脸分割，以便于将生成的脸贴会到原始的脸上。在实时口型推理场景，人脸分割可以提前进行并存储，我们预计在接下来两周内release用于实时口型推理场景的素材准备代码与实时推理代码。

要是能接近两三秒生成，那就完美了。

**Comment by itechmusic** [comment]
我们更新了实时推理代码 https://github.com/TMElyralab/MuseTalk?tab=readme-ov-file#new-real-time-inference

这个代码也可以显著提升用不同音频驱动同一个视频的速度。
