### ISSUE TITLE
如何实现实时视频生成

### ISSUE THREAD

**Issue by XM233333333** [TMElyralab/MuseTalk#26]
During online chatting, only UNet and the VAE decoder are involved, which makes MuseTalk real-time.

这个应该怎么做？

**Comment by huyppppppp** [comment]
> During online chatting, only UNet and the VAE decoder are involved, which makes MuseTalk real-time.
> 
> 这个应该怎么做？

请问您有什么好办法吗

**Comment by itechmusic** [comment]
Hello, we release codes for real time inference here https://github.com/TMElyralab/MuseTalk?tab=readme-ov-file#new-real-time-inference

**Comment by XM233333333** [comment]
Thank you ，let me have a try.
