### ISSUE TITLE
imageio_ffmpeg saving video error

### ISSUE THREAD

**Issue by KevinWang676** [TMElyralab/MuseTalk#27]
Hi, can anyone help me resolve this issue? Thank you!

I encountered the error below when running `app.py`, specifically `imageio.mimwrite(output_video, images, 'FFMPEG', fps=fps, codec='libx264', pixelformat='yuv420p')`

Error message:
```
File "/usr/local/lib/python3.10/dist-packages/imageio_ffmpeg/_io.py", line 627, in write_frames p.stdin.write(bb) BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by itechmusic** [comment]
> Hi, can anyone help me resolve this issue? Thank you!
> 
> I encountered the error below when running `app.py`, specifically `imageio.mimwrite(output_video, images, 'FFMPEG', fps=fps, codec='libx264', pixelformat='yuv420p')`
> 
> Error message:
> 
> ```
> File "/usr/local/lib/python3.10/dist-packages/imageio_ffmpeg/_io.py", line 627, in write_frames p.stdin.write(bb) BrokenPipeError: [Errno 32] Broken pipe
> ```

DId you install `ffmpeg`?

**Comment by KevinWang676** [comment]
no, i tried to install `ffmpeg`, but it turned out that `ffmpeg-python` was the correct one to install. only installing `ffmpeg` will lead to another error.

**Comment by KevinWang676** [comment]
@itechmusic i am really interested in your work and many applications can be built upon it. do you mind having a further discussion with me? my email accout is talktalkai.kevin@gmail.com 
please feel free to contact me! Thanks!

**Comment by theoldsong** [comment]
最后一步，合成视频的时候遇到了同样的问题，ffmpeg安装过了

**Comment by theoldsong** [comment]
而且自带的app.py是不是用不了？

**Comment by itechmusic** [comment]
> 而且自带的app.py是不是用不了？

hello，我们刚更新了app.py，现在应该可以了

**Comment by theoldsong** [comment]
> > 而且自带的app.py是不是用不了？
> 
> hello，我们刚更新了app.py，现在应该可以了

好的，我试试，感谢！
