### ISSUE TITLE
近景时候嘴部会变得奇怪且很模糊，中景时候就挺好的， 希望修复下，感谢作者

### ISSUE THREAD

**Issue by T8mars** [TMElyralab/MuseTalk#28]
近景时候嘴部会变得奇怪且很模糊，中景时候就挺好的， 希望修复下，感谢作者

**Comment by ferrymo** [comment]
+1

**Comment by aidenyzhang** [comment]
训练数据的人脸区域是resize到256X256的。
对于中景来说，脸部区域占256，原视频已经是720P甚至1080P的。训练数据也大多是是这种情况。
人脸占比较大（大于256）的近景数据在训练集中出现的也不多，inference效果会有折扣。
