### ISSUE TITLE
能否增加个在线驱动的例子和代码，那样直接秒杀其他数字人了

### ISSUE THREAD

**Issue by anstonjie** [TMElyralab/MuseTalk#3]
能否增加个在线驱动的例子和代码，那样直接秒杀其他数字人了

**Comment by ApolloRay** [comment]
他这个实时应该还是做不到在线驱动，还是有delay。

**Comment by itechmusic** [comment]
当前在固定了视频素材后，对视频提前进行预处理（人脸检测、vae-encode等）。线上只进行推理与vae-decode，在V100上是可以达到30fps的推流实时的。

我们后续会提供这部分的代码，预计在4月内。

**Comment by anstonjie** [comment]
太棒了，支持你们










在 2024-04-08 13:33:30，"itechmusic" ***@***.***> 写道：

当前在固定了视频素材后，对视频提前进行预处理（人脸检测、vae-encode等）。线上只进行推理与vae-decode，在V100上是可以达到30fps的推流实时的。

我们后续会提供这部分的代码，预计在4月内。

**Comment by Xmenlin** [comment]
> 当前在固定了视频素材后，对视频提前进行预处理（人脸检测、vae-encode等）。线上只进行推理与vae-decode，在V100上是可以达到30fps的推流实时的。
> 
> 我们后续会提供这部分的代码，预计在4月内。

非常期待！

**Comment by itechmusic** [comment]
实时推理代码示例已更新 https://github.com/TMElyralab/MuseTalk?tab=readme-ov-file#new-real-time-inference
