### ISSUE TITLE
进程挂掉后，可否根据之前的内容继续生成

### ISSUE THREAD

**Issue by ChjxL** [TMElyralab/MuseTalk#44]
目前遇到进程挂掉后，之前生成的png图片有保存，但是不能断点接续，有没有方法可以接着之前的生成内容继续生成。

**Comment by itechmusic** [comment]
理论上应该可行的。但抱歉，目前我们可能没有时间支持这个功能。

**Comment by ChjxL** [comment]
我想了一个蠢方法，将已经生成的png用ffmpeg合成视频，再将未生成的重新生成
