### ISSUE TITLE
斜脸生成效果不好

### ISSUE THREAD

**Issue by jkla139** [TMElyralab/MuseTalk#45]
不清楚是不是因为面部在边缘，关键点检测不够准确导致的 

https://github.com/TMElyralab/MuseTalk/assets/44624598/fe318972-da03-4cec-b4a6-a5736fe8b9ad

https://github.com/TMElyralab/MuseTalk/assets/44624598/f80f718b-a32d-4006-9ec9-eb97802d29a3

**Comment by itechmusic** [comment]
这个视频倾斜的角度太大了，训练集里可能没有很好地覆盖这种情况。可以考虑先做一个rotation把脸旋转正，理论上不会有太多清晰度损失。

**Comment by xuhongming251** [comment]
我验证了，效果还行，分享在这里，兄弟们，来三连！https://b23.tv/9ZgRi6x

I tested it out, and it's not too shabby, sharing it here. Guys, come and triple likes! https://b23.tv/9ZgRi6x
