### ISSUE TITLE
有计划支持华为的昇腾平台吗

### ISSUE THREAD

**Issue by xunnew** [TMElyralab/MuseTalk#46]
有计划支持华为的昇腾平台吗

**Comment by itechmusic** [comment]
不好意思，我们不太熟悉昇腾平台，暂时没有这个计划

**Comment by yaleimeng** [comment]
理论上应该是NPU厂商提供驱动和工具包对接运算框架（tf、paddle、torch等）和底层运算库。上层代码跑通是自然而然的事情。
