### ISSUE TITLE
为什么上传的视频会被加速和压缩？

### ISSUE THREAD

**Issue by ferrymo** [TMElyralab/MuseTalk#47]
我在以下环境进行测试
https://huggingface.co/spaces/TMElyralab/MuseTalk
使用的MuseV生成的8s视频，在上述环境上传后就变成了2s ，可以解答一下嘛

**Comment by itechmusic** [comment]
请问方便分享一下你的视频吗？我们测试一下。 在上述的环境，因为保证体验，会把fps太小的视频转换成25fps（不然fps太低口型的准确性体现不出来），但是正常来说不应该改变时长才对。

**Comment by ferrymo** [comment]
> 请问方便分享一下你的视频吗？我们测试一下。 在上述的环境，因为保证体验，会把fps太小的视频转换成25fps（不然fps太低口型的准确性体现不出来），但是正常来说不应该改变时长才对。

@itechmusic  ，感谢您的回复， github无法上传原视频 提醒超过10MB，我截图给你下，如果有需要我邮箱发你下也行
我补充下，使用自己录制的视频不会出现该问题，出现问题的是使用MuseV生成的视频如下（帧数参数我记得是6）：
![image](https://github.com/TMElyralab/MuseTalk/assets/52627295/835b2585-85b6-4315-9023-7842f5d1d9b9)

上传后只剩余2s，直接看下来只是做了加速压缩了，效果如下

https://github.com/TMElyralab/MuseTalk/assets/52627295/40d389e0-032b-4691-aeae-2c05be9dc4e8

**Comment by itechmusic** [comment]
> > 请问方便分享一下你的视频吗？我们测试一下。 在上述的环境，因为保证体验，会把fps太小的视频转换成25fps（不然fps太低口型的准确性体现不出来），但是正常来说不应该改变时长才对。
> 
> @itechmusic ，感谢您的回复， github无法上传原视频 提醒超过10MB，我截图给你下，如果有需要我邮箱发你下也行 我补充下，使用自己录制的视频不会出现该问题，出现问题的是使用MuseV生成的视频如下（帧数参数我记得是6）： ![image](https://private-user-images.githubusercontent.com/52627295/326142040-835b2585-85b6-4315-9023-7842f5d1d9b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxODM0NjAsIm5iZiI6MTcxNDE4MzE2MCwicGF0aCI6Ii81MjYyNzI5NS8zMjYxNDIwNDAtODM1YjI1ODUtODViNi00MzE1LTkwMjMtNzg0MmY1ZDFkOWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDAxNTkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhYzU3YjU5MDRhZmI1ODdhMWI5NzFjMzAwOTM5ZGQwNjY0YjI4MGMxNDZmMDczNDFjYzYzOGMxODk2ZGZkZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O6cDKtMl6sLYPKqCZv4sOl5snAfxjZzKS_udMMhaaxw)
> 
> 上传后只剩余2s，直接看下来只是做了加速压缩了，效果如下： ![image](https://private-user-images.githubusercontent.com/52627295/326143039-744851a6-a281-49f1-a80b-687f0b3c97a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxODM0NjAsIm5iZiI6MTcxNDE4MzE2MCwicGF0aCI6Ii81MjYyNzI5NS8zMjYxNDMwMzktNzQ0ODUxYTYtYTI4MS00OWYxLWE4MGItNjg3ZjBiM2M5N2E0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDAxNTkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkMGIzNmI0ODMzZmM4ZDkxYWFkM2YzMjQyODkyODRlYjdlYTBlMDU4MDVhNmFhOTc2YmFhMDhmZjQwMjQzNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U8JILDKpeuedCccJViHo-6fJnT5MnZZbSnd1VJj65Cw)
> 
> 我把上传后的视频从新下载了下，效果如下：
> 
>  outputxxx_1.mp4

hello, 研究了一下，是space里代码从6fps转成25fps有bug，没有通过补帧的方式实现，所以导致时长被压缩了 https://github.com/TMElyralab/MuseTalk/blob/main/app.py#L354

在我们修复前，你可以先把视频从6fps补帧成25fps使用，如`ffmpeg -i input.mp4 -r 25 output.mp4`

**Comment by itechmusic** [comment]
这个问题应该已经被修复了。目前https://huggingface.co/spaces/TMElyralab/MuseTalk会正确地把视频转换成25fps

**Comment by ferrymo** [comment]
@itechmusic 已经可以了，谢谢
