### ISSUE TITLE
为什么realtime脚本生成用时，比日志显示的fps实际要慢很多？

### ISSUE THREAD

**Issue by jercas** [TMElyralab/MuseTalk#49]
- 生成数据：均使用的测试样例（video: sun.mp4 |  audio: yongen.wav）；
- 使用脚本：realtime_inference，已提前完成avater数据的抽取，仅仅进行语音片段生成；
- 问题1：202帧的片段，日志显示平均fps为77.5
    - 此处为什么每四帧处理一次，且第一帧的处理速度要远远慢于后者（10 >> 100）？ 
<img width="640" alt="image" src="https://github.com/TMElyralab/MuseTalk/assets/27855802/a8db1c14-7500-4843-beea-c2bc691bf210">

- 问题2：按fps推算，202处理完总共应只需几秒钟，但实际打点的耗时为23s（未统计后续的帧+音频合成视频的时间）
<img width="1131" alt="image" src="https://github.com/TMElyralab/MuseTalk/assets/27855802/9d4b0421-630f-4b7a-909b-b8a7ab50d27d">

**Comment by jercas** [comment]
@itechmusic 感谢回复！
我这边是按照realtime_inference的pipline启动跑的，并没有看到单独启线程进行图片处理的部分，这边看到图片的存储实在realtime_inference.procees_frames() func里，紧接着image_blending之后处理的。

请问这拆分存储、拼接对的部分代码在哪个模块，或者是否有参照的脚本呢？

**Comment by itechmusic** [comment]
hello，不好意思，目前发现这个脚本有些bug，速度不太正常。我们正在修复

**Comment by kingsaction** [comment]
png能否不落地，常驻内存，后面在落到磁盘

**Comment by itechmusic** [comment]
目前代码已经修复，加入了float16使推理速度达到30fps+。速度会受I/O影响，可以使用`python -m scripts.realtime_inference --inference_config configs/inference/realtime.yaml --skip_save_images`命令跳过保存png，单纯体验推理速度。

**Comment by jercas** [comment]
hi，经过测试后，skip_save_images看起来并没有减少I/O的损失，这里的硬件是V100，测试的日志如下：

- 存图片
<img width="1358" alt="image" src="https://github.com/TMElyralab/MuseTalk/assets/27855802/408bb2af-2826-46ad-a542-eb4a70a89281">


- 不存图片
<img width="1363" alt="image" src="https://github.com/TMElyralab/MuseTalk/assets/27855802/11887818-2d3c-4162-be2d-fb9e747c9573">

**Comment by itechmusic** [comment]
> hi，经过测试后，skip_save_images看起来并没有减少I/O的损失，测试的日志如下：
> 
> * 硬件：V100 * 1；
> * 样例：测试case中的sun视频+音频。
> * 存图片
> 
> <img alt="image" width="1358" src="https://private-user-images.githubusercontent.com/27855802/326247346-7913ad03-e67c-419d-b8b1-390b12d89d01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMDAxMjIsIm5iZiI6MTcxNDI5OTgyMiwicGF0aCI6Ii8yNzg1NTgwMi8zMjYyNDczNDYtNzkxM2FkMDMtZTY3Yy00MTlkLWI4YjEtMzkwYjEyZDg5ZDAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDEwMjM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3Njk4N2I1OTIwZTJjYzFjYjRkZmI2YWI5YzI4ZmJmZjEwYzU5NWM3Mzc1ODBkZjIyMjkxZjExNDE4NGZmMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sL_EELzTClDhIzkqImIcSN4lni1Go-g5FEo2QVCxFw4">
> * 不存图片
> 
> <img alt="image" width="1352" src="https://private-user-images.githubusercontent.com/27855802/326247204-3879a882-14dd-4f73-8862-2d1a90eb851e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMDAxMjIsIm5iZiI6MTcxNDI5OTgyMiwicGF0aCI6Ii8yNzg1NTgwMi8zMjYyNDcyMDQtMzg3OWE4ODItMTRkZC00ZjczLTg4NjItMmQxYTkwZWI4NTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDEwMjM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMWU1MWI5ODU4YzY4ZTE2MDFmMGRhNzdlZjc1NjRjODMwNjg0NGYyOTI3ZWE3Y2ZkZTk0NWUxZWJkMThmMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SxPOBLQTTsByWgFsodDzzG3VJCqZzi7vVstRzBljFsc">

hello，第一次运行时可能会有模型warm up导致的耗时。这是我们在V100上用`batch_size=8`的结果
![image](https://github.com/TMElyralab/MuseTalk/assets/163980830/f57b9805-e6f6-4db5-9cd6-3496c0b120c9)

**Comment by jercas** [comment]
感谢~  依照测试，warmup的问题确实会一定程度上影响Infer速率，我依照你的测试配置，跑了几版测试，但fps还是远低于图例，请问其中差距 问题大概在哪呢？
- 测试视频 sun.mp4，测试音频[yongen.wav, sun.wav, yongen.wav, sun.wav]，已提前进行avater抽取

<img width="2771" alt="image" src="https://github.com/TMElyralab/MuseTalk/assets/27855802/c98c26d7-e393-4ea7-a36a-2997eab4f1c7">

**Comment by itechmusic** [comment]
> 感谢~ 依照测试，warmup的问题确实会一定程度上影响Infer速率，我依照你的测试配置，跑了几版测试，但fps还是远低于图例，请问其中差距 问题大概在哪呢？
> 
> * 测试视频 sun.mp4，测试音频[yongen.wav, sun.wav, yongen.wav, sun.wav]，已提前进行avater抽取
> * 硬件v100-SXM2-32GB * 1, bs=8
> 
> <img alt="image" width="2000" src="https://private-user-images.githubusercontent.com/27855802/326253596-c98c26d7-e393-4ea7-a36a-2997eab4f1c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMDYyMzEsIm5iZiI6MTcxNDMwNTkzMSwicGF0aCI6Ii8yNzg1NTgwMi8zMjYyNTM1OTYtYzk4YzI2ZDctZTM5My00ZWE3LWEzNmEtMjk5N2VhYjRmMWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDEyMDUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxZDc5YjQ2ZDEwMjQ1NDc3NWU4ZTQwNzIyNWQ1MmE2ZTU4M2E4OGRlMWI1ZjYyYmRlZTViYWZhYThjNDNlYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vxFPxQRZz5na9QlecN0Rxkl6tsZ7qp01LWeChmN2048">

有点不知道原因。。。请问有试过换一张卡测试吗？

**Comment by sswax000643** [comment]
遇到同样的问题，无法复现出图示的速度

**Comment by Siziff** [comment]
@itechmusic  How can I keep the model in memory so that I can inference the models faster?

**Comment by FreddyChant** [comment]
> > hi，经过测试后，skip_save_images看起来并没有减少I/O的损失，测试的日志如下：
> > 
> > * 硬件：V100 * 1；
> > * 样例：测试case中的sun视频+音频。
> > * 存图片
> > 
> > <img alt="image" width="1358" src="https://private-user-images.githubusercontent.com/27855802/326247346-7913ad03-e67c-419d-b8b1-390b12d89d01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMDAxMjIsIm5iZiI6MTcxNDI5OTgyMiwicGF0aCI6Ii8yNzg1NTgwMi8zMjYyNDczNDYtNzkxM2FkMDMtZTY3Yy00MTlkLWI4YjEtMzkwYjEyZDg5ZDAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDEwMjM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3Njk4N2I1OTIwZTJjYzFjYjRkZmI2YWI5YzI4ZmJmZjEwYzU5NWM3Mzc1ODBkZjIyMjkxZjExNDE4NGZmMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sL_EELzTClDhIzkqImIcSN4lni1Go-g5FEo2QVCxFw4">
> > * 不存图片
> > <img alt="image" width="1352" src="https://private-user-images.githubusercontent.com/27855802/326247204-3879a882-14dd-4f73-8862-2d1a90eb851e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMDAxMjIsIm5iZiI6MTcxNDI5OTgyMiwicGF0aCI6Ii8yNzg1NTgwMi8zMjYyNDcyMDQtMzg3OWE4ODItMTRkZC00ZjczLTg4NjItMmQxYTkwZWI4NTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDEwMjM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMWU1MWI5ODU4YzY4ZTE2MDFmMGRhNzdlZjc1NjRjODMwNjg0NGYyOTI3ZWE3Y2ZkZTk0NWUxZWJkMThmMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SxPOBLQTTsByWgFsodDzzG3VJCqZzi7vVstRzBljFsc">
> 
> hello，第一次运行时可能会有模型warm up导致的耗时。这是我们在V100上用`batch_size=8`的结果 ![image](https://github.com/TMElyralab/MuseTalk/assets/163980830/f57b9805-e6f6-4db5-9cd6-3496c0b120c9)

您好，我想问下单卡和多卡怎么进行推理加速，谢谢
