### ISSUE TITLE
add dubbing example code

### ISSUE THREAD

**Issue by jackleibest** [TMElyralab/MuseTalk#51]
it is a nice project, seems it is supports video dubbing, so please add dubbing example code

**Comment by itechmusic** [comment]
Hi, you could just run `python -m scripts.inference --inference_config configs/inference/test.yaml 
` following https://github.com/TMElyralab/MuseTalk?tab=readme-ov-file#inference. There is no difference between video dubbing and making virtual character talk in terms of codes so far.
