### ISSUE TITLE
训练过程的问题

### ISSUE THREAD

**Issue by ljiqy** [TMElyralab/MuseTalk#73]
你好，我有一个问题请教下，就是我在准备训练数据的时候需要保存npy文件，每个npy文件应该是要按顺序保存whisper_feature里的(2, 5, 384)对吗？因为我看推理的时候get_sliced_feature函数选的是（10, 5, 384），而训练的DataLoader.py里是选的相邻的总共5个npy，所以每个npy应该是（2,5,384）。这样理解对吗？

**Comment by aidenyzhang** [comment]
> 你好，我有一个问题请教下，就是我在准备训练数据的时候需要保存npy文件，每个npy文件应该是要按顺序保存whisper_feature里的(2, 5, 384)对吗？因为我看推理的时候get_sliced_feature函数选的是（10, 5, 384），而训练的DataLoader.py里是选的相邻的总共5个npy，所以每个npy应该是（2,5,384）。这样理解对吗？

对的。
