### ISSUE TITLE
Who needs high-quality lip sync - contact me!

### ISSUE THREAD

**Issue by Chechgroup** [TMElyralab/MuseTalk#74]
I can do lip sync for any character. I reduced the quality to 10 MB in order to upload video. If you are interested, write to me in telegram: The_best_result

https://github.com/TMElyralab/MuseTalk/assets/152233811/13cb4484-10c4-45fe-8d97-25a244cdfc7e

https://github.com/TMElyralab/MuseTalk/assets/152233811/b5ed20da-3822-45ba-91f4-42c28fe8787f

https://github.com/TMElyralab/MuseTalk/assets/152233811/c1bd1e6b-7ce5-4e66-a26e-d6ee6e4ccff4

**Comment by xunnew** [comment]
do you have chinese demo
