### ISSUE TITLE
生成结果视频不连续，黑屏

### ISSUE THREAD

**Issue by missu263** [TMElyralab/MuseTalk#79]
生成结果在12秒时候，就没有画面了。原视频50多秒

使用素材
https://github.com/TMElyralab/MuseTalk/assets/15882147/91062cd4-dc8e-4c11-9357-20d801a93f03

音频：`audio_path: "data/audio/sun.wav"`

生成结果如下
https://github.com/TMElyralab/MuseTalk/assets/15882147/3b507621-565c-4bde-8711-4e2a9dbfa059

**Comment by alexLIUMinhao** [comment]
Hi， 

Your footage has not been edited well, and it contains many non-human scenes, which may cause the face detection model to fail. Therefore, please prepare a clip that includes frontal human subjects for testing.

**Comment by panjie-payne** [comment]
> Hi，
> 
> Your footage has not been edited well, and it contains many non-human scenes, which may cause the face detection model to fail. Therefore, please prepare a clip that includes frontal human subjects for testing.

在有些场景下， 视频中间可能会穿插一些没有人脸的场景， 怎么避免因为出现没有人脸场景导致黑屏的问题呢

**Comment by praymich** [comment]
> > Hi，
> > Your footage has not been edited well, and it contains many non-human scenes, which may cause the face detection model to fail. Therefore, please prepare a clip that includes frontal human subjects for testing.
> 
> 在有些场景下， 视频中间可能会穿插一些没有人脸的场景， 怎么避免因为出现没有人脸场景导致黑屏的问题呢

我也有这个问题，请问你解决了吗
