### ISSUE TITLE
画面静止不动了

### ISSUE THREAD

**Issue by Weststreet** [TMElyralab/MuseTalk#87]
非常感谢贡献这么棒的项目，在使用过程中遇到一个问题，我用7分钟的音频以及30s的视频，最终合成出来的视频之播放了十几秒后面的画面就静止不动了，而且前十几秒的口型也完全没对上，请问这是山原因呢。windows 11 RTX 4070ti 16G

**Comment by czk32611** [comment]
您好，请问用其他音频与视频正常吗？

**Comment by Weststreet** [comment]
> 您好，请问用其他音频与视频正常吗？

相同的视频我试了另一个18秒的音频效果还是蛮好的。而且在我多次测试发现，总是会有某些音频会出现以上问题，不知道是不是因为音频的某些参数跟视频不匹配？

**Comment by Weststreet** [comment]
> 您好，请问用其他音频与视频正常吗？


https://github.com/TMElyralab/MuseTalk/assets/11329810/ff8f4ed1-5004-45ca-ba83-06e662cdecb4

类似这样的问题

**Comment by Weststreet** [comment]
> 您好，请问用其他音频与视频正常吗？



> 您好，请问用其他音频与视频正常吗？

之前有问题的音视频使用python -m scripts.realtime_inference --inference_config configs/inference/realtime.yaml --batch_size 4命令行之后就没问题了，我先关掉问题，后续发现其他问题再继续反馈
