### ISSUE TITLE
Runetime error in huggingface

### ISSUE THREAD

**Issue by JARVISMindEngineer** [TMElyralab/MuseTalk#88]
1. https://huggingface.co/spaces/TMElyralab/MuseTalk
<img width="1150" alt="image" src="https://github.com/TMElyralab/MuseTalk/assets/165481157/628566aa-876f-4e4e-8702-5fe4593d9945">
2. what time need to generate a 10second video?

**Comment by czk32611** [comment]
1. The space is restarted.
2. The time needed depends on the GPU used actually. We do not have an actual measurement so far. The pre-processing takes more time than inference actually.
