### ISSUE TITLE
多卡训练超时问题

### ISSUE THREAD

**Issue by ljiqy** [TMElyralab/MuseTalk#93]
用2张A800卡跑训练，出现卡住不动的问题，等待一段时间报错，请问这是什么原因
![微信截图_20240521181009](https://github.com/TMElyralab/MuseTalk/assets/37796840/0d282f43-3ede-49ae-86eb-a8ba1c0d6662)

**Comment by gobigrassland** [comment]
看看Dataset这块，如果某一步，每张卡上batch数量不一致，就会导致上述问题。
