### ISSUE TITLE
参考视频>25FPS需要如何处理

### ISSUE THREAD

**Issue by sj123sheng** [TMElyralab/MuseTalk#94]
如原视频为30FPS或者60FPS 是先将原视频变成25FPS然后再生成吗 还是在执行的时候加上--fps 30(对应视频真实数值)来处理效果更好

**Comment by czk32611** [comment]
hello，没有测试过这种情况的效果，你可以对比一下，代码是支持直接推理30fps和60fps的，会自动识别视频的fps

**Comment by sj123sheng** [comment]
> hello，没有测试过这种情况的效果，你可以对比一下，代码是支持直接推理30fps和60fps的，会自动识别视频的fps

你好，代码里好像没看到不输入--fps参数，会自动识别视频的fps的逻辑，好像会按照默认的25FPS值来处理？

**Comment by sj123sheng** [comment]
![image](https://github.com/TMElyralab/MuseTalk/assets/17697535/2a11a6d8-a7f8-4b06-93ce-c55a3c10086b)
![image](https://github.com/TMElyralab/MuseTalk/assets/17697535/31c72687-1f26-4db5-ba8e-319be6e31afd)
![image](https://github.com/TMElyralab/MuseTalk/assets/17697535/bba53e48-8c67-40fb-9983-2fef6ebcbc24)

我发现原视频30fps，生成视频的时候没有输入fps参数，生成的视频就变成25fps了

**Comment by czk32611** [comment]
> ![image](https://private-user-images.githubusercontent.com/17697535/335106100-2a11a6d8-a7f8-4b06-93ce-c55a3c10086b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjgxMTAsIm5iZiI6MTcxNzA2NzgxMCwicGF0aCI6Ii8xNzY5NzUzNS8zMzUxMDYxMDAtMmExMWE2ZDgtYTdmOC00YjA2LTkzY2UtYzU1YTNjMTAwODZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDExMTY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmZjYyOTNkZDUzZGRmNDIwZmQzMGM0YzQ5ODgwNTk4MmRhZjQ1MzAzMTlmNDExNTMxZGIxOGE1NTdmYTQ3MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UzQ9m8bYjS2e_wIMjiL43W83gUri7WpTXdmMfSFklCs) ![image](https://private-user-images.githubusercontent.com/17697535/335106236-31c72687-1f26-4db5-ba8e-319be6e31afd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjgxMTAsIm5iZiI6MTcxNzA2NzgxMCwicGF0aCI6Ii8xNzY5NzUzNS8zMzUxMDYyMzYtMzFjNzI2ODctMWYyNi00ZGI1LWJhOGUtMzE5YmU2ZTMxYWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDExMTY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzNTkyNDVjY2EyODM4M2UyNjUwMGQyNWZkZWJhZWViZjQyMjdjNWMyMzM5ZDRhZmMzZmY2MDNlODZjNjI1Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i_FHc5-_n8VEdCUauGfYJ79mCu0Re7AW_TuOAhgZeeU) ![image](https://private-user-images.githubusercontent.com/17697535/335106575-bba53e48-8c67-40fb-9983-2fef6ebcbc24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjgxMTAsIm5iZiI6MTcxNzA2NzgxMCwicGF0aCI6Ii8xNzY5NzUzNS8zMzUxMDY1NzUtYmJhNTNlNDgtOGM2Ny00MGZiLTk5ODMtMmZlZjZlYmNiYzI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDExMTY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5N2NkNDFhZDUyYmFlYjAxMjM4MzhhZmE0Y2UzOGQ3ZGIxMjk5YmI0ZDRiODIyYTY5OWUxZjIxM2QyYjA3ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jEdGja94oeWMg69RrRUMk_y25CObi5Bx1hpz9PWWKXw)
> 
> 我发现原视频30fps，生成视频的时候没有输入fps参数，生成的视频就变成25fps了

`realtime_inference.py`因为是会预先存储视觉素材，没有保存fps，按照25fps处理了。 `inference.py`会按照视频fps进行推理。

我们是建议使用25fps进行推理的，因为训练是用25fps。
