### ISSUE TITLE
about bbox shift

### ISSUE THREAD

**Issue by TigerHH6866** [TMElyralab/MuseTalk#96]
when source video is people talking,normarlly, and get Manually adjust range -x~y,
now what bbox shift value should i use??
or how to get the right value? any suggestion?

**Comment by gobigrassland** [comment]
@czk32611 关于这个问题，发布的这个模型，在训练过程中，是固定mask掉下半张脸即mask[128:256, :] = 0吗？还是让mask的上边界根据计算出的可调整幅度，在训练过程中在这个合理范围随机选择呢？

**Comment by czk32611** [comment]
> 即mas

目前模型训练时是固定mask掉下半张脸即mask[128:256, :] = 0

**Comment by czk32611** [comment]
> when source video is people talking,normarlly, and get Manually adjust range -x~y, now what bbox shift value should i use?? or how to get the right value? any suggestion?

You can find more explanation of bbox_shift [here](https://github.com/TMElyralab/MuseTalk/blob/main/assets/BBOX_SHIFT.md)
