### ISSUE TITLE
different audio problem

### ISSUE THREAD

**Issue by TigerHH6866** [TMElyralab/MuseTalk#97]
by using audio 1(the one  target avatar speaking) to create avatar
then using audio 2(different people)
lipsync result seems to be different??
is it limited to use audio same as avatar created?

**Comment by czk32611** [comment]
It should work in your case. Creating avatar only pre-save vision information. Could you share your results?

**Comment by TigerHH6866** [comment]
> It should work in your case. Creating avatar only pre-save vision information. Could you share your results?

found that using different people audio get little different result. so i turn to bbox -30 close lip firstly.
then all comes same result
