### ISSUE TITLE
视频唇部抖动非常明显

### ISSUE THREAD

**Issue by JenjiLee** [TMElyralab/MuseTalk#98]
https://github.com/TMElyralab/MuseTalk/assets/55727788/64d4668d-3b31-46c3-9ae7-5f5c75d0a5e6

只用了inference，保存透明通道后

**Comment by JenjiLee** [comment]
输入数据格式是webm，（保留alpha通道），是需要重新训练吗

**Comment by czk32611** [comment]
看起来是人脸检测和人脸抠图的效果不稳定。请问有试过把alpha换成白色背景或者灰色背景吗？

**Comment by DestoryVIP** [comment]
请问一下这种webm的视频是如何保存的？
