### ISSUE TITLE
cu118  需要什么 torch  和xformers版本 

### ISSUE THREAD

**Issue by pantherliu** [TMElyralab/MuseTalk#99]
各种尝试还是不能解决，不知道为啥 有人分享下 cuda11.8的配置文件名啊，多谢多谢

**Comment by czk32611** [comment]
你可以试一下torch==2.0.1+cu118, xformers==0.0.21

**Comment by TigerHH6866** [comment]
> 你可以试一下torch==2.0.1+cu118, xformers==0.0.21

xformers需要单独安装么？怎么使用xformers加速呢？

**Comment by czk32611** [comment]
> > 你可以试一下torch==2.0.1+cu118, xformers==0.0.21
> 
> xformers需要单独安装么？怎么使用xformers加速呢？

需要单独pip install。目前没有使用xformers，可以参考[diffusers](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/modeling_utils.py#L213)进行使用
